# 開発用 Docker 構成
# db のみコンテナとして起動します。web, rest は npm と JRE で起動してください。
version: "2"
services:
  # データベース
  db:
    image: mongo:3.4.9
    ports:
    - 27017:27017
    volumes:
    - data-volume:/data/db
volumes:
  data-volume:
