version: "2"
services:
  # フロントエンド
  web:
    build: web
    ports:
    - "80:80"
    volumes:
    - ./web/src:/usr/share/nginx/html
    environment:
    - REST_HOST=http://localhost:8080
  # データベース: 27017
  db:
    image: mongo:3.4.9
    ports:
    - 27017:27017
    volumes:
    - data-volume:/data/db
volumes:
  data-volume:
