# デバッグ用 Docker 構成（REST なし）
version: "2"
services:
  # フロントエンド
  web:
    build: web
    ports:
    - "80:80"
    args:
      build_mode: "debug"
  # データベース: 27017
  db:
    image: mongo:3.4.9
    ports:
    - 27017:27017
    volumes:
    - data-volume:/data/db
volumes:
  data-volume:
