version: "2"
services:
  # フロントエンド
  # web:

  # REST サーバー（開発用）を起動します
  rest:
    command: "stack exec rest"
    build: .
    ports:
    - "8080:8080"
    # stdin_open: true
    # tty: true
  # データベース
  db:
    image: mongo:3.4.9
    ports:
    - "27017:27017"
  # データベース（永続化用ボリューム）
  # data:
  #   image: mongo:3.4.9
