version: "2"
services:
  # フロントエンド
  web:
    build: web
    ports:
    - "80:80"
    volumes:
    - ./web/src:/usr/share/nginx/html
  # データベース: 27017
  db:
    image: mongo:3.4.9
    ports:
    - 27017:27017
