# テスト用 Docker 構成
version: "2"
services:
  # REST サーバー（開発用）
  rest:
    build:
      # https://docs.docker.com/engine/reference/commandline/build/#extended-description
      context: rest
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: material_explorer
      IMAGEMAGICK_HOST: im
      MANIFEST: ./manifest.yaml
      REPOSITORIES: ./repositories.yaml
      # GITLAB_PERSONAL_ACCESS_TOKEN:
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./temp/log/material-explorer:/var/log/material-explorer
      - ./conf/config.test.yaml:/opt/material-explorer/config.test.yaml
      - ./conf/manifest.yaml:/opt/material-explorer/manifest.yaml
      - ./conf/repositories.yaml:/opt/material-explorer/repositories.yaml
  # フロントエンド ウェブサーバー（開発用）
  web:
    build:
      context: web
      args:
        service_host: "http://localhost:8080"
    ports:
      - 80:80
  # データベース
  db:
    image: mongo:3.4.9
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db
  # ImageMagick
  im:
    build:
      context: im
volumes:
  data-volume:
