version: "2"
services:
  # フロントエンド
  web:
    build: web
    ports:
    - "80:80"
  # REST サーバー（開発用）を起動します
  rest:
    command: "stack exec rest"
    build: rest
    ports:
    - "8080:8080"
    # stdin_open: true
    # tty: true
  # データベース: 27017
  db:
    image: mongo:3.4.9

