name: material-explorer
version: '0.1.0.0'
category: Web
author: OPAP-JP
maintainer: bromne@opap.jp
copyright: 2017 OPAP
license: BSD3
github: opap-jp/material-explorer
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Lib
  dependencies:
  - base >=4.7 && <5
executables:
  material-explorer-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - material-explorer
tests:
  material-explorer-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - material-explorer
flags:
  library-only:
    manual: false
    default: false
